import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '../styles/Home.module.css'

import type { AppProps } from 'next/app'
import TheHeader from '../components/layout/TheHeader';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return <div className={styles.container}>
    <Head>
      <title>Portfolio of Bruno Lamps</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <TheHeader />
    <Component {...pageProps} />
  </div>
}

export default MyApp
